{
    'name': 'University',
    'version': '1.0',
    'summary': 'University management module',
    'author': 'Jesus Rodriguez',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/mail_template.xml',  
        'views/university_views.xml',
        'views/department_views.xml',
        'views/teacher_views.xml',
        'views/subject_views.xml',
        'views/student_views.xml',
        'views/enrollment_views.xml',
        'views/grade_views.xml',
        'views/university_report_views.xml',
        'views/menu.xml',
        'reports/student_report.xml',
        'reports/student_report_template.xml',
    ],
    'application': True,
}